CI: Downgrade PostgreSQL integration test to use Python 3.13 again
fatal error: librdkafka/rdkafka.h: No such file or directory
 23 | #include <librdkafka/rdkafka.h>
    |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
error: command '/usr/bin/gcc' failed with exit code 1

hint: This error likely indicates that you need to install a library
that provides "librdkafka/rdkafka.h" for `confluent-kafka@2.8.0`
help: `confluent-kafka` (v2.8.0) was included because
`cratedb-toolkit[io-ingestr]` (v0.0.0) depends on `ingestr` (v0.14.96)
which depends on `confluent-kafka`

=> Why is the PostgreSQL integration using Kafka anyway? ;]